name: Auto Train Model

on:
  push:
    branches: [main]

jobs:
  train:
    runs-on: self-hosted
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    steps:
      - uses: actions/checkout@v5

      - run: py -3.12 --version

      - run: py -3.12 -m pip install --upgrade pip

      - run: py -3.12 -m pip install -r requirements.txt

      - run: py -3.12 train.py
